spring:
  application:
    name: eureka-server

server:
  port: 8761

logging:
  level:
    com.netflix: debug

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761
  server:
    enable-self-preservation: false